### ISSUE TITLE
Questions about Code

### ISSUE THREAD

**Issue by ShaohuaL** [yzbouc/UVEB#8]
您好，我在程序运行时候遇到以下问题，还望您百忙之中解答：
1，在ReadMe中提到的 python setup.py develop 请问这个功能的用处是什么？如果我只是希望test您发布的代码和程序，是否必须要运行这个命令？
2，关于 Dataset Organization Form， 请问 test 阶段 blur 文件夹和 gt 文件夹内容可以一样吗？对于每个video，例如 video 1，其下面文件夹中 frame1 frame2 是否有明确的命名要求？还是说按照0001 0002 或者 a001 a0002等存在先后顺序的命名即可？
3，我在运行test.py代码时候报错提示： 
basicsr/archs/deblur_arch.py", line 75, in forward
    b, t, c, h, w = lrs.size()
ValueError: not enough values to unpack (expected 5, got 4)
请问这个lrs 变量的理论形状是什么呀？ b的含义是什么？ 

还望您帮忙解答，谢谢。

**Comment by yzbouc** [comment]
1.We use setup.py help establish the environment, our code was modified based on Basicsr, hoping to save time on writing programs such as dataloader. It is recommended to install according to the instructions, and the requirements for the pytorch version are not strict. 2. The following figure shows our test data naming method and composition form.Actually, all the data is split into frames that are close to 5TB, so we cannot upload images.
![example](https://github.com/yzbouc/UVEB/assets/66795226/344ad0ec-1e8a-4bc7-bc35-edee6b93d60e)  
3.b：batchsize，t：frame，c：channel，h：height，w：width.

**Comment by yzbouc** [comment]
1.We use setup.py help establish the environment, our code was modified based on Basicsr, hoping to save time on writing programs such as dataloader. It is recommended to install according to the instructions, and the requirements for the pytorch version are not strict. 
2. The following figure shows our test data naming method and composition form. Actually, splitting all videos into frames takes up nearly 5TB of memory.
![example](https://github.com/yzbouc/UVEB/assets/66795226/c5306055-ec9a-445c-92c0-eecbfad4fc3a)
3.b：batchsize，t：frame，c：channel，h：height，w：width.

**Comment by ShaohuaL** [comment]
Thanks for your patient reply!
